USE xdc;

DROP TABLE Account;

CREATE TABLE Account(
aid BIGINT PRIMARY KEY AUTO_INCREMENT,
accName VARCHAR(30) NOT NULL,
userPswd VARCHAR(20) NOT NULL,
email VARCHAR(30) NOT NULL
);

CREATE TABLE AccountSsid(
aid BIGINT PRIMARY KEY,
ssid CHAR(16) NOT NULL
);